version: '3'

services:
  php:
    build:
      context: docker/php
    volumes:
      - .:/app
      - composer-volume:/app/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.config/psysh:/root/.config/psysh
    command: ["php", "artisan", "serve", "--host", "0.0.0.0"]
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_DATABASE: laravel_development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
  node:
    image: node:12
    volumes:
      - .:/app
      - node-modules-volume:/app/node_modules
    working_dir: /app
volumes:
  composer-volume:
  node-modules-volume:
  mysql-volume:
